export const routes = {
  root: 'mordisco',
  home: '/album/2022MAY',
  albums: '/album/2022MAY', // First album
  defaultCover: '/default-cover.gif',
}

export const ALBUMS = [
  {
    folder: '2022NOV',
    title: 'Fabrizio Mammarella, Yahaira',
    year: 2022,
    month: 'Noviembre',
    length: 0,
    cover: 'https://res.cloudinary.com/nvzf/image/upload/v1669413702/mordisco/2022NOV/2905.jpg',
  },
  {
    folder: '2022MAY',
    title: 'Budino, Moderna',
    year: 2022,
    month: 'Mayo',
    length: 0,
    cover: 'https://res.cloudinary.com/nvzf/image/upload/v1667052285/mordisco/2022MAY/2222.jpg',
  },
  {
    folder: '2022MAR',
    title: 'Shubostar',
    year: 2022,
    month: 'Marzo',
    length: 0,
    cover: 'https://res.cloudinary.com/nvzf/image/upload/v1667096402/mordisco/2022MAR/1675.jpg',
  },
  {
    folder: '2020FEB',
    title: 'Eagles & Butterflies',
    year: 2020,
    month: 'Febrero',
    length: 0,
    cover:
      'https://res.cloudinary.com/nvzf/image/upload/v1668211358/mordisco/2020FEB/3036656966366357.jpg',
  },
  {
    folder: '2019NOV',
    title: 'Curses',
    year: 2019,
    month: 'Noviembre',
    length: 0,
    cover:
      'https://res.cloudinary.com/nvzf/image/upload/v1668212375/mordisco/2019NOV/2832408496791206.jpg',
  },
]

export const quotes = [
  {
    text: 'Hubo signos, señales, pero qué hacer si no eran comprensibles.',
    author: 'Wislawa Szymborska',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Banderas, dejad ya de taparnos los ojos.',
    author: 'Adam Zagajewski',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Un día encontraré las palabras adecuadas y serán simples.',
    author: 'Jack Kerouac',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Sacrificar el nombre de las cosas para ganar su presencia',
    author: 'Roberto Juarroz',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Si no hay mucho que decir, al menos, tu voz.',
    author: 'Ángel Gabilondo',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Nos oímos y cada uno escucha tan sólo una voz que está dentro de él.',
    author: 'Fernando Pessoa',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Algo falta y hay que ponerle nombre.',
    author: 'Blanca Andreu',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Si las verdades dijeran la verdad mentirían.',
    author: 'Ángeles Mora',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Todas las divisiones son mentira salvo la que divide los cuerpos en dos.',
    author: 'Ben Clark',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Las palabras no son signos, son años.',
    author: 'Octavio Paz',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Banderas, dejad ya de taparnos los ojos.',
    author: 'Adam Zagajewski',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Un día encontraré las palabras adecuadas y serán simples.',
    author: 'Jack Kerouac',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Si las verdades dijeran la verdad mentirían.',
    author: 'Ángeles Mora',
    party: 'Curses',
    year: '',
  },
  {
    text: '¿Has pensado ya cuán invisibles somos los unos para los otros?',
    author: 'Fernando Pessoa',
    party: 'Curses',
    year: '',
  },
  {
    text: 'Si el amor es esto, no lo quiero',
    author: 'Albert Cohen',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'Eres una persona tan extraordinaria como todas las demás',
    author: 'José Miguel Valle',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'Dos seres que se aman forman uno solo: ¿cuál de ellos?',
    author: 'Nancy Huston',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'Todos somos mortales hasta el primer beso',
    author: 'Eduardo Galeano',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'Estar enamorado es un estado; amar, un acto',
    author: 'Denis de Rougemont',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: "Don't try to fix him",
    author: '@toilets_queens_berlin',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'El amor existe para que estallen los relojes',
    author: 'Cristina Peri Rossi',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: '¿Cómo puedo dar media vuelta para elegirme a mí?',
    author: 'Rupi Kaur',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'Ver lo que tenemos delante de nuestras narices requiere una lucha constante',
    author: 'George Orwell',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'Amarse a una misma es algo punk, es algo revolucionario, es algo radical',
    author: 'Judith Duportail',
    party: 'Fabrizio Mammarella',
    year: '',
  },
  {
    text: 'Siempre estamos ligados de una u otra manera al resto',
    author: 'Lynn Margulis',
    party: 'Lauer y Undo',
    year: '',
  },
  {
    text: 'El otro lado es el mayor contagio',
    author: 'Roberto Juarroz',
    party: 'Lauer y Undo',
    year: '',
  },
  {
    text: 'No se hace un mundo con simples átomos',
    author: 'Jean Luc Nancy',
    party: 'Lauer y Undo',
    year: '',
  },
  {
    text: 'LESS EGO IS MORE FUTURE',
    author: 'Christoph Thun Hohenstein',
    party: 'Lauer y Undo',
    year: '',
  },
  { text: 'Mañana es la cuestión', author: 'Rikrit Tiravanija', party: 'Lauer y Undo', year: '' },
  { text: 'Sin vosotros, la nada.', author: 'Javier Egea', party: 'Lauer y Undo', year: '' },
  {
    text: 'El nuevo Lampedusa es tu piel',
    author: 'Paul B. Preciado',
    party: 'Lauer y Undo',
    year: '',
  },
  {
    text: 'Somos una especie que no posee una importancia especial',
    author: 'Slavoj Zizek',
    party: 'Lauer y Undo',
    year: '',
  },
  {
    text: 'Conocemos el sonido de la palmada de dos manos, pero ¿Cuál es el sonido de la palmada de una sola mano?',
    author: 'Koan Zen',
    party: 'Lauer y Undo',
    year: '',
  },
  {
    text: 'En el centro del vacío hay otra fiesta',
    author: 'Roberto Juarroz',
    party: 'Moderna y Budino',
    year: '2014',
  },
  {
    text: 'Para vivir un año es necesario morirse muchas veces mucho',
    author: 'Ángel González',
    party: 'Moderna y Budino',
    year: '2015',
  },
  {
    text: 'Si cierro los ojos puedo imaginarme en un futuro echando de menos este instante',
    author: 'Javier Román',
    party: 'Moderna y Budino',
    year: '2016',
  },
  {
    text: 'Caminando en línea recta no puede llegar uno muy lejos',
    author: 'Antoine de Saint-Exupéry',
    party: 'Moderna y Budino',
    year: '2013',
  },
  {
    text: 'Ojalá tires tu reloj al agua',
    author: 'Val del Omar',
    party: 'Moderna y Budino',
    year: '2012',
  },
  {
    text: 'Quien mira el firmamento elige la locura',
    author: 'José Manuel Caballero Bonald',
    party: 'Moderna y Budino',
    year: '2017',
  },
  {
    text: 'El mundo comenzó sin el hombre, y terminará sin él',
    author: 'Claude Lévi-Strauss',
    party: 'Moderna y Budino',
    year: '2012',
  },
  {
    text: 'No sucede nada, no temas. Sólo es el tiempo',
    author: 'Karmelo C. Iribarren',
    party: 'Moderna y Budino',
    year: '2015',
  },
  {
    text: 'Hacer una buena fiesta es poner en movimiento una onda inolvidable',
    author: 'Brandon Labelle',
    party: 'Moderna y Budino',
    year: '2022',
  },
  {
    text: 'Nunca es tarde para encontrarnos en el patio del recreo.',
    author: 'Alejandra Vanessa',
    party: 'Moderna y Budino',
    year: '2018',
  },
  {
    text: 'All things are delicately interconected',
    author: 'Jenny Holzer',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'La vida pueda estar de pronto en el silencio o la mirada.',
    author: 'Julia Prilutzky',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'Para quien ve en la noche no una negación de la luz, sino más bien su estado extremo',
    author: 'Pepe Espaliú',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'La vida existía sin nosotros y seguirá sin nosotros',
    author: 'Lynn Margulis',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'Lo que queda sería suficiente si durase',
    author: 'Ángel González',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'Hacer una buena fiesta es poner en movimiento una onda inolvidable',
    author: 'Brandon Labelle',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'Quién sabe si el futuro nos depara algo nuevo',
    author: 'Patricia Manrique',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'La pandemia es la demostración de que todos estamos unidos por un cordón invisible',
    author: 'Gabriel Markus',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'Nada hay más común que ser: es la evidencia de la existencia',
    author: 'Jean Luc Nancy',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
  {
    text: 'El baile letal de los hombres entrará en declive y empezará a surgir un nuevo baile',
    author: 'Larry Mitchell',
    party: 'Shubostar y Alvaro Cabana',
    year: '',
  },
]
